// Copyright 2018 The Bazel Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import * as vscode from "vscode";

import { BazelWorkspaceInfo, QueryLocation } from "../bazel";
import { getTargetsForBuildFile } from "../bazel";
import { getDefaultBazelExecutablePath } from "../extension/configuration";
import { blaze_query } from "../protos";
import { CodeLensCommandAdapter } from "./code_lens_command_adapter";

/** Computes the shortened name of a Bazel target.
 *
 * For example, if the target name starts with `//foo/bar/baz:fizbuzz`,
 * the target's short name will be `fizzbuzz`.
 *
 * This allows our code lens suggestions to avoid filling users' screen with
 * redundant path information.
 *
 * @param targetName The unshortened name of the target.
 * @returns The shortened name of the target.
 */
function getTargetShortName(targetName: string): string {
  const colonFragments = targetName.split(":");
  if (colonFragments.length !== 2) {
    return targetName;
  }
  return colonFragments[1];
}

/** Provides CodeLenses for targets in Bazel BUILD files. */
export class BazelBuildCodeLensProvider implements vscode.CodeLensProvider {
  public onDidChangeCodeLenses: vscode.Event<void>;

  /** Fired when BUILD files change in the workspace. */
  private onDidChangeCodeLensesEmitter = new vscode.EventEmitter<void>();

  /**
   * Initializes a new CodeLens provider with the given extension context.
   *
   * @param context The VS Code extension context.
   */
  constructor(private context: vscode.ExtensionContext) {
    this.onDidChangeCodeLenses = this.onDidChangeCodeLensesEmitter.event;

    const buildWatcher = vscode.workspace.createFileSystemWatcher(
      "**/{BUILD,BUILD.bazel}",
      true, // ignoreCreateEvents
      false,
      true, // ignoreDeleteEvents
    );
    buildWatcher.onDidChange(
      () => {
        this.onDidChangeCodeLensesEmitter.fire();
      },
      this,
      context.subscriptions,
    );

    vscode.workspace.onDidChangeConfiguration((change) => {
      if (change.affectsConfiguration("bazel.enableCodeLens")) {
        this.onDidChangeCodeLensesEmitter.fire();
      }
    });
  }

  /**
   * Provides promisified CodeLen(s) for the given document.
   *
   * @param document A Bazel BUILD file
   * @param token CodeLens token automatically generated by VS Code when
   * invoking the provider
   */
  public async provideCodeLenses(
    document: vscode.TextDocument,
  ): Promise<vscode.CodeLens[]> {
    const bazelConfig = vscode.workspace.getConfiguration("bazel");
    const enableCodeLens = bazelConfig.get<boolean>("enableCodeLens");
    if (!enableCodeLens) {
      return [];
    }

    if (document.isDirty) {
      // Don't show code lenses for dirty BUILD files; we can't reliably
      // determine what the build targets in it are until it is saved and we can
      // invoke `bazel query` with the updated file.
      return [];
    }

    const workspaceInfo = BazelWorkspaceInfo.fromDocument(document);
    if (workspaceInfo === undefined) {
      // Not in a Bazel Workspace.
      return [];
    }

    const queryResult = await getTargetsForBuildFile(
      getDefaultBazelExecutablePath(),
      workspaceInfo.bazelWorkspacePath,
      document.uri.fsPath,
    );

    return this.computeCodeLenses(workspaceInfo, queryResult);
  }

  /**
   * Takes the result of a Bazel query for targets defined in a package and
   * returns a list of CodeLens for the BUILD file in that package.
   *
   * @param bazelWorkspaceInfo The Bazel workspace information containing workspace path and context
   * @param queryResult The result of the bazel query containing target definitions
   * @returns A new array of CodeLens objects for the BUILD file
   */
  private computeCodeLenses(
    bazelWorkspaceInfo: BazelWorkspaceInfo,
    queryResult: blaze_query.QueryResult,
  ): vscode.CodeLens[] {
    const result: vscode.CodeLens[] = [];

    // Sort targets by length first, then alphabetically, keeping private
    // ("_"-prefixed) targets last. This ensures shorter names (often the main
    // targets) appear first, with consistent ordering within each length group.
    const sortedTargets = [...queryResult.target].sort((a, b) => {
      const aPrivate = a.rule.name.startsWith("_");
      const bPrivate = b.rule.name.startsWith("_");
      if (aPrivate !== bPrivate) {
        return aPrivate ? 1 : -1;
      }
      const lengthDiff = a.rule.name.length - b.rule.name.length;
      return lengthDiff !== 0
        ? lengthDiff
        : a.rule.name.localeCompare(b.rule.name);
    });

    // Group targets by line number to handle multiple targets on same line
    const targetsByLine = new Map<number, typeof sortedTargets>();
    for (const target of sortedTargets) {
      const location = new QueryLocation(target.rule.location);
      const line = location.line;
      if (!targetsByLine.has(line)) {
        targetsByLine.set(line, []);
      }
      targetsByLine.get(line)?.push(target);
    }

    // Process each line's targets
    for (const [, targets] of targetsByLine) {
      this.createCodeLensesForTargetsOnSameLine(
        targets,
        bazelWorkspaceInfo,
        result,
      );
    }

    return result;
  }

  /**
   * Creates CodeLens objects for targets on the same line.
   *
   * Each target gets its own "Copy label" lens. When many targets share a
   * line, only the first few are shown and the remainder are collapsed into a
   * single summary lens to avoid cluttering the editor.
   *
   * @param targets Array of Bazel targets found on the same line in the BUILD file
   * @param bazelWorkspaceInfo Workspace context information for command creation
   * @param result Output array that will be modified in-place to include new CodeLens objects
   */
  private createCodeLensesForTargetsOnSameLine(
    targets: blaze_query.ITarget[],
    bazelWorkspaceInfo: BazelWorkspaceInfo,
    result: vscode.CodeLens[],
  ): void {
    const location = new QueryLocation(targets[0].rule.location);
    const totalAtLine = targets.length;
    let added = 0;

    for (const target of targets) {
      // Collapse if there are more than 5 targets on this line and we've
      // already shown 3; the rest are summarized by a single lens.
      if (totalAtLine > 5 && added >= 3) {
        const remaining = totalAtLine - added;
        result.push(
          new vscode.CodeLens(location.range, {
            command: "", // No-op / empty lens
            title: `(${remaining} more targets)`,
            tooltip: `${remaining} more targets hidden`,
          }),
        );
        break;
      }

      const targetName = target.rule.name;
      // Show the target's short name so each lens identifies its own target.
      const title = getTargetShortName(targetName);
      result.push(
        new vscode.CodeLens(location.range, {
          arguments: [
            new CodeLensCommandAdapter(bazelWorkspaceInfo, [targetName]),
          ],
          command: "bazel.copyLabelToClipboard",
          title,
          tooltip: targetName,
        }),
      );
      added++;
    }
  }
}
